<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <?=$this->headMeta()?>
        <?=$this->headTitle('AddressBook')->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <link rel="stylesheet" href="<?=$this->basePath('css/bootstrap.css')?>">
        <?=$this->headLink()?>
        
        <?=$this->headStyle()?>
        
        <?=$this->headScript()?>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$this->url('home')?>">AddressBook</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Contacts <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?=$this->url('contact')?>">List</a></li>
                                <li><a href="<?=$this->url('contact/add')?>">Ajouter</a></li>
                            </ul>
                        </li>
                    </ul>
<!--                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Link</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </li>
                    </ul>-->
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container -->
        </nav>
        
        <div class="container">
            <?=$this->content?>
        </div>
        
        <script src="<?=$this->basePath('js/jquery.min.js')?>"></script>
        <script src="<?=$this->basePath('js/bootstrap.min.js')?>"></script>
        <?=$this->inlineSCript()?>
    </body>
</html>
